### ISSUE TITLE
Can it be compiled for Windows.

### ISSUE THREAD

**Issue by saurabhgayali** [fmaguire/WoLFPSort#4]
If yes please add a few lines about it.

**Comment by DanBuchan** [comment]
The answer to this question is almost certainly yes. You'd probably might have more/easier success compiling with CYGWin or MinGW

**Comment by fmaguire** [comment]
I rehosted this project as the original website died. The original source files were never released so only the compiled i386 and sparc binaries are available: see #3

**Comment by DanBuchan** [comment]
FWIW I have finally tracked down Paul Horton's contact details and I have emailed him about releasing the source code.

**Comment by saurabhgayali** [comment]
I wanted a native Windows support for running as local server under xampp. I am Windows user and I prefer it that way. I have virtualbox but due to less RAM it slows down my PC. Moreover running virtualbox all the time won't be good. Vagrant and docker are new to me. So I am (was stuck).

Strangely GITBash (MingW64) is running the executable. I hope to make the server from here.

**Comment by saurabhgayali** [comment]
Ran command
`./runWolfPsortHtmlTables plant out test.fasta`
where test.fasta contains 3 sequences
out folder exists

output
```
Error: psort classical predictions expects a dbm file:
psortModifiedForWolfFiles/attribute.dir or
psortModifiedForWolfFiles/attribute, but cannot find it.
Your choices are:


1. create the dbm files with:
  % cd bin/psortModifiedForWolfFiles
  % ./psortModifiedForWoLF -t all.seq

2. Run this program  with --no-classical-psort-prediction or
   --no-classical-psort-verbose-output options

```

Ran command
`./runWolfPsortHtmlTables --no-classical-psort-prediction plant  out test.fasta`

Bash hangs indefinitely.

I am still on Windows 7 with Mingw64 as my bash.

**Comment by saurabhgayali** [comment]
Apparently the runWolfPsortHtmlTables and runWolfPsortSummary are perl files and therefore they worked under mingW.
Both file do call for executables wolfPredict which is linux executable binary and hence showing error in windows under MingW.

**Comment by fmaguire** [comment]
As discussed in the other issue linked and above: unfortunately, we can't recompile it currently due to no sources. The compiled binaries are the actual trained prediction models instead of just the perl glue scripts.  You can always try traces and hacking in the missing libraries but if you really want to run it but currently the easiest way is to just use a linux system/VM.  

As a general comment you will find most bioinformatics tool much easier to run on linux that windows.
